apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "endorser_api.fullname" . }}
  labels:
    {{- include "endorser_api.labels" . | nindent 4 }}
data:
  IMAGE_TAG: {{ .Values.endorser_api.image.tag | quote }}
  IMAGE_VERSION: {{ .Values.endorser_api.image.version | quote }}
  IMAGE_BUILDTIME: {{ .Values.endorser_api.image.buildtime | quote }}