apiVersion: v1
kind: Service
metadata:
  name: {{ include "endorser_api.fullname" . }}
  labels:
    {{- include "endorser_api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.endorser_api.service.type }}
  ports:
    - port: {{ .Values.endorser_api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "endorser_api.selectorLabels" . | nindent 4 }}