apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acapy.fullname" . }}-config
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
data:
  argfile.yml: |
    {{- if (index .Values "acapy" "argfile.yml") }}
    {{- include "common.tplvalues.render" ( dict "value" (index .Values "acapy" "argfile.yml") "context" $) | nindent 4 }}
    {{- end }}
  plugin-config.yml: |
    {{- if index .Values "acapy" "plugin-config.yml" }}
    {{- include "common.tplvalues.render" ( dict "value" (index .Values "acapy" "plugin-config.yml") "context" $) | nindent 4 }}
    {{- end }}
  multi-ledger-config.yml: |
    {{- if index .Values "acapy" "multi-ledger-config.yml" }}
    {{- include "common.tplvalues.render" ( dict "value" (index .Values "acapy" "multi-ledger-config.yml") "context" $) | nindent 4 }}
    {{- end }}
