apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acapy.fullname" . }}-config
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
data:
  argfile.yml: |
    {{- range $elem, $elemVal := index .Values "argfile.yml" }}
      {{- if not (kindIs "map" $elemVal) }}
      {{- if kindIs "invalid" $elemVal }}
      {{ $elem }} =
      {{- else if kindIs "string" $elemVal }}
      {{ $elem }} = {{ tpl $elemVal $ }}
      {{- else }}
      {{ $elem }} = {{ $elemVal }}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- range $key, $value := index .Values "argfile.yml" }}
      {{- if kindIs "map" $value }}
      [{{ $key }}]
      {{- range $elem, $elemVal := $value }}
      {{- if kindIs "invalid" $elemVal }}
      {{ $elem }} =
      {{- else if kindIs "string" $elemVal }}
      {{ $elem }} = {{ tpl $elemVal $ }}
      {{- else }}
      {{ $elem }} = {{ $elemVal }}
      {{- end }}
      {{- end }}
      {{- end }}
    {{- end }}
  plugin-config.yml: |
    {{- range $elem, $elemVal := index .Values "plugin-config.yml" }}
      {{- if not (kindIs "map" $elemVal) }}
      {{- if kindIs "invalid" $elemVal }}
      {{ $elem }} =
      {{- else if kindIs "string" $elemVal }}
      {{ $elem }} = {{ tpl $elemVal $ }}
      {{- else }}
      {{ $elem }} = {{ $elemVal }}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- range $key, $value := index .Values "plugin-config.yml" }}
      {{- if kindIs "map" $value }}
      [{{ $key }}]
      {{- range $elem, $elemVal := $value }}
      {{- if kindIs "invalid" $elemVal }}
      {{ $elem }} =
      {{- else if kindIs "string" $elemVal }}
      {{ $elem }} = {{ tpl $elemVal $ }}
      {{- else }}
      {{ $elem }} = {{ $elemVal }}
      {{- end }}
      {{- end }}
      {{- end }}
    {{- end }}
