name: Read Manifests
description: Read Manifest Repository
inputs:
  repository_key:
    required: true
    type: string
  repository:
    required: true
    type: string
  repository_checkout_path:
    required: true
    type: string
    default: read-manifests
  charts_path:
    required: true
    type: string
    default: charts/traction
  target:
    required: true
    type: string
    default: 'dev'


outputs:
  release_version:
    description: "Release Version"
    value: ${{ steps.values.outputs.release_version }}
  api_image_tag:
    description: "Traction API Image Tag"
    value: ${{ steps.values.outputs.api_image_tag }}
  api_image_version:
    description: "Traction API Image Version"
    value: ${{ steps.values.outputs.api_image_version }}
  api_image_buildtime:
    description: "Traction API Image Buildtime"
    value: ${{ steps.values.outputs.api_image_buildtime }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Check out manifest repo
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ inputs.repository_key }}
        repository: ${{ inputs.repository }}
        path: ${{ inputs.repository_checkout_path }}
    
    - id: release_version
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.release.version' './${{ inputs.repository_checkout_path }}/${{ inputs.charts_path }}/values-${{ inputs.target }}.yaml'      

    - id: api_image_tag
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.traction_api.image.tag' './${{ inputs.repository_checkout_path }}/${{ inputs.charts_path }}/values-${{ inputs.target }}.yaml'      

    - id: api_image_version
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.traction_api.image.version' './${{ inputs.repository_checkout_path }}/${{ inputs.charts_path }}/values-${{ inputs.target }}.yaml'      

    - id: api_image_buildtime
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.traction_api.image.buildtime' './${{ inputs.repository_checkout_path }}/${{ inputs.charts_path }}/values-${{ inputs.target }}.yaml'       

    - id: values
      name: Set output values 
      shell: bash
      run: |
        echo "::set-output name=release_version::${{ steps.release_version.outputs.result }}"
        echo "::set-output name=api_image_tag::${{ steps.api_image_tag.outputs.result }}"
        echo "::set-output name=api_image_version::${{ steps.api_image_version.outputs.result }}"
        echo "::set-output name=api_image_buildtime::${{ steps.api_image_buildtime.outputs.result }}"
