apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "global.fullname" . }}-ingress-nsp
  labels:
    {{- include "common.selectorLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "tenant_proxy.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  policyTypes:
    - Ingress