apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "traction_api.fullname" . }}
  labels:
    {{- include "traction_api.labels" . | nindent 4 }}
data:
  IMAGE_TAG: {{ .Values.traction_api.image.tag | quote }}
  IMAGE_VERSION: {{ .Values.traction_api.image.version | quote }}
  IMAGE_BUILDTIME: {{ .Values.traction_api.image.buildtime | quote }}