apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "global.fullname" . }}-nsp
  labels:
    {{- include "common.selectorLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      'app.kubernetes.io/instance': {{ template "global.fullname" . }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          'app.kubernetes.io/instance': {{ template "global.fullname" . }}
