apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ template "showcase.secret.name" . }}
  labels:
    {{- include "common.selectorLabels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  admin_pwd: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "showcase.secret.name" .) "Key" "admin_pwd") }}
  user_pwd: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "showcase.secret.name" .) "Key" "user_pwd") }}
