apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "showcase.fullname" . }}
  labels:
    {{- include "showcase.labels" . | nindent 4 }}
data:
  IMAGE_TAG: {{ .Values.showcase.image.tag | quote }}
  IMAGE_VERSION: {{ .Values.showcase.image.version | quote }}
  IMAGE_BUILDTIME: {{ .Values.showcase.image.buildtime | quote }}
