apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ include "tenant-ui.fullname" . }}
  labels:
    {{- include "tenant-ui.selectorLabels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.traction.pluginInnkeeper.existingSecret }}
  tenantid: {{ include "getFromSecret" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" .Values.traction.pluginInnkeeper.existingSecret "Key" "tenantid") }}
  walletkey: {{ include "getFromSecret" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" .Values.traction.pluginInnkeeper.existingSecret "Key" "walletkey") }}
  {{ else }}
  tenantid: {{ .Values.traction.pluginInnkeeper.tenantid | b64enc }}
  walletkey: {{ .Values.traction.pluginInnkeeper.walletkey | b64enc }}
  {{- end }}
