apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tenant_ui.fullname" . }}
  labels:
    {{- include "tenant_ui.labels" . | nindent 4 }}
data:
  IMAGE_TAG: {{ .Values.tenant_ui.image.tag | quote }}
  IMAGE_VERSION: {{ .Values.tenant_ui.image.version | quote }}
  IMAGE_BUILDTIME: {{ .Values.tenant_ui.image.buildtime | quote }}
