{{- if .Values.global.nsp.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tenant_ui.fullname" . }}-ingress-nsp
  labels:
    {{- include "tenant_ui.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "tenant_ui.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  policyTypes:
    - Ingress
{{- end }}