global:
  fullnameOverride: "pr-00-tenant-ui"
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca
tenant_ui:
  image:
    tag: "ghcr.io/bcgov/traction-tenant-ui:sha-87c2eb2"
    version: 'sha-87c2eb2'
    buildtime: '2022-01-20T22:37:11.102Z'
    pullPolicy: Always
  traction_api:
    endpoint: https://pr-00-traction-api-dev.apps.silver.devops.gov.bc.ca
  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi