global:
  fullnameOverride: 'pr-00-tenant-ui'
  tractionNameOverride: "pr-00-traction"
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca
tenant_ui:
  image:
    tag: 'ghcr.io/bcgov/traction-tenant-ui:sha-5fdc664'
    version: 'sha-5fdc664'
    buildtime: '2022-08-04T22:16:25.869Z'
    pullPolicy: Always
  traction_api:
    endpoint: https://pr-00-traction-api-dev.apps.silver.devops.gov.bc.ca
  acapy_admin_api:
    endpoint: https://pr-00-traction-acapy-admin-dev.apps.silver.devops.gov.bc.ca
  oidc:
    active: true
    showInnkeeperAdminLogin: true
    authority: https://dev.loginproxy.gov.bc.ca/auth/realms/digitaltrust-nrm
    jwksUri: https://dev.loginproxy.gov.bc.ca/auth/realms/digitaltrust-nrm/protocol/openid-connect/certs
  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi