version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: false
    config:
      threshold: 250
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: false
    config:
      threshold: 20
  method-lines:
    enabled: false
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
exclude_patterns:
- ".pytest_cache/"
- ".tox/"
- ".github/"
- ".vscode/"
- "acapy_client/"
- "acapy_wrapper/"
- "api/db/migrations/"
- "bdd-tests/"
- "tests/"
- "venv/"
- ".coverage"
- "acapy-*.json"
- "conftest.py"
- "setup.py"
