global:
  fullnameOverride: "pr-00-showcase"
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca
postgresql:
  fullnameOverride: 'pr-00-showcase'
  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi
showcase:
  image:
    tag: "ghcr.io/bcgov/traction-showcase:sha-87c2eb2"
    version: 'sha-87c2eb2'
    buildtime: '2022-01-20T22:37:11.102Z'
    pullPolicy: Always
  config:
    webConcurrency: 2
  traction_api:
    endpoint: https://pr-00-traction-api-dev.apps.silver.devops.gov.bc.ca
    secret:
      name: pr-00-traction-api
  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi