# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  nameOverride: ""
  # global.fullnameOverride and postgresql.fullnameOverride must be changed (and match!!!) if deploying multiple instances to the same namespace
  # the postgresql chart creates secrets and pvcs related to the fullname and will be identical without the override.
  # use the global.fullnameOverride to install a different named helm instance and will affect naming of all objects and routes for that chart.
  # for pull requests, can set to something like pr-NN-showcase.
  fullnameOverride: "showcase"

  # -- Domain suffix to be used for default hostpaths in ingress
  # override in different environments, or for each app
  # --set global.ingressSuffix
  ingressSuffix: -prod.apps.silver.devops.gov.bc.ca

  persistence:
    # -- If true, the Postgres chart is deployed
    deployPostgres: true

showcase:
  image:
    tag: "ghcr.io/bcgov/traction-showcase:sha-aa006f2"
    version: 'sha-aa006f2'
    buildtime: '2022-01-20T22:37:11.102Z'
    pullPolicy: IfNotPresent

  config:
    gunicornWorkers: 2

  db:
    admin: showcaseadminuser
    user: showcaseuser

  traction_api:
    # this is the public endpoint
    endpoint: https://traction-api-prod.apps.silver.devops.gov.bc.ca
    # this must match the value in the matching traction deployment, see traction/charts/values.yaml
    adminuser: innkeeper
    secret:
      # this will be traction-api, or pr-##-traction-api
      name: traction-api

  serviceAccount:
    # -- Specifies whether a service account should be created
    create: false
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
    name: ""

  imagePullSecrets: []

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 5000

  openshift:
    route:
      enabled: true
      path: "/"
      targetPort: http
      timeout: 2m
      tls:
        enabled: true
        insecureEdgeTerminationPolicy: None
        termination: edge
      wildcardPolicy: None

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 600m
      memory: 2600Mi
    requests:
      cpu: 300m
      memory: 1300Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

postgresql:
  # when overriding global.fullnameOverride, you must override this to match.
  fullnameOverride: "showcase"

  image:
    tag: 12

  # --  PostgreSQL service configuration
  service:
    port: 5432

  existingSecret: '{{ template "postgresql.secret.name" . }}'

  # -- PostgreSQL Database to create.
  postgresqlDatabase: showcase

  extraEnv:
    - name: ADMIN_PWD
      valueFrom:
        secretKeyRef:
          key: admin_pwd
          name: '{{ template "showcase.secret.name" . }}'
    - name: USER_PWD
      valueFrom:
        secretKeyRef:
          key: user_pwd
          name: '{{ template "showcase.secret.name" . }}'

  lifecycleHooks:
    postStart:
      exec:
        command:
          - '/bin/bash'
          - '-c'
          - |
            sleep 30;
            USER_LOG=/dev/shm/01_user.log
            if [ -s "$USER_LOG" ]; then
              echo "$USER_LOG exists with data."
            else
              echo "$USER_LOG does not exist or has no data."
              user_sql=$(cat <<-EOF
                CREATE USER showcaseadminuser PASSWORD '$ADMIN_PWD';
                CREATE USER showcaseuser PASSWORD '$USER_PWD';
                ALTER DATABASE showcase OWNER TO showcaseadminuser;
            EOF
            )
            echo $user_sql > /dev/shm/01_user.sql
            echo $user_sql | psql "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$HOSTNAME" -o /dev/shm/01_user.log
            fi

            SCHEMA_LOG=/dev/shm/02_schema.log
            if [ -s "$SCHEMA_LOG" ]; then
              echo "$SCHEMA_LOG exists with data."
            else
              echo "$SCHEMA_LOG does not exist or has no data."
              schema_sql=$(cat <<-EOF
                CREATE EXTENSION IF NOT EXISTS pgcrypto;
                REVOKE ALL ON SCHEMA public FROM PUBLIC;
                GRANT USAGE ON SCHEMA public TO showcaseadminuser;
                GRANT USAGE ON SCHEMA public TO showcaseuser;
                GRANT ALL ON SCHEMA public TO showcaseadminuser;
                ALTER DEFAULT PRIVILEGES FOR USER showcaseadminuser IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO showcaseuser;
                ALTER DEFAULT PRIVILEGES FOR USER showcaseadminuser IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO showcaseuser;
                ALTER DEFAULT PRIVILEGES FOR USER showcaseadminuser IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO showcaseuser;
            EOF
            )
            echo $schema_sql > /dev/shm/02_schema.sql
            echo $schema_sql | psql "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$HOSTNAME/$POSTGRES_DB" -o /dev/shm/02_schema.log
            fi

  # --  Persistent Volume Storage configuration. ref: https://kubernetes.io/docs/user-guide/persistent-volumes
  persistence:
    enabled: true
    size: 1Gi
    storageClass: netapp-file-standard

  # -- add securityContext (fsGroup, runAsUser). These need to be false for Openshift 4
  securityContext:
    enabled: false

  containerSecurityContext:
    enabled: false

  resources:
    limits:
      cpu: 600m
      memory: 2600Mi
    requests:
      cpu: 300m
      memory: 1300Mi

