global:
  fullnameOverride: "pr-00-traction"
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca
acapy:
  image:
    tag: "ghcr.io/bcgov/traction-plugins-acapy:sha-f594a33"
    version: 'sha-f594a33'
    buildtime: '2023-03-01T03:07:45.860Z'
    pullPolicy: Always
  secret:
    adminurl:
      generated: false
    pluginInnkeeper:
      generated: false
  pluginValues:
    tractionInnkeeper:
      printKey: true
      printToken: true
      reservationExpiryMinutes: 120
  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi
  tails:
    enabled: true
postgresql:
  fullnameOverride: 'pr-00-traction'
  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi
tenant_proxy:
  image:
    tag: "ghcr.io/bcgov/traction-tenant-proxy:sha-f594a33"
    version: 'sha-f594a33'
    buildtime: "2023-03-01T03:07:43.994Z"
    pullPolicy: Always