global:
  fullnameOverride: "pr-00-traction"
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca
acapy:
  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi
postgresql:
  fullnameOverride: 'pr-00-traction'
  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi
traction_api:
  image:
    tag: "ghcr.io/bcgov/traction-api:sha-1a21896"
    version: 'sha-1a21896'
    buildtime: '2022-01-20T22:37:11.102Z'
    pullPolicy: Always
  config:
    gunicornWorkers: 1
  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi
