global:
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca
acapy:
  image:
    tag: "ghcr.io/bcgov/traction-plugins-acapy:sha-25c438d"
    version: 'sha-25c438d'
    buildtime: '2022-10-28T01:30:31.105Z'
    pullPolicy: Always
  secret:
    adminurl:
      generated: false
    pluginInnkeeper:
      generated: false
  pluginValues:
    tractionInnkeeper:
      printKey: true
      printToken: true
      reservationExpiryMinutes: 120
  resources:
    limits:
      cpu: 400m
      memory: 1600Mi
    requests:
      cpu: 200m
      memory: 820Mi
  tails:
    enabled: true
postgresql:
  resources:
    limits:
      cpu: 400m
      memory: 1600Mi
    requests:
      cpu: 200m
      memory: 820Mi
traction_api:
  image:
    tag: "ghcr.io/bcgov/traction-api:sha-2aa3709"
    version: 'sha-2aa3709'
    buildtime: "2022-01-28T18:19:10.574Z"
    pullPolicy: Always
  secret:
    apiAdminKey:
      generated: false
  config:
    webConcurrency: 2
  resources:
    limits:
      cpu: 400m
      memory: 1600Mi
    requests:
      cpu: 200m
      memory: 820Mi
