global:
  fullnameOverride: "pr-00-traction"
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca
acapy:
  tails:
    enabled: true
postgresql:
  fullnameOverride: 'pr-00-traction'
traction_api:
  image:
    tag: "ghcr.io/bcgov/traction-api:sha-87c2eb2"
    version: 'sha-87c2eb2'
    buildtime: '2022-01-20T22:37:11.102Z'
    pullPolicy: Always

