global:
  fullnameOverride: "pr-00-traction"
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca
acapy:
  image:
    repository: 
    tag: "ghcr.io/bcgov/traction-plugins-acapy:sha-25c438d"
    version: 'sha-25c438d'
    buildtime: '2022-10-28T01:30:31.105Z'
    pullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi
  tails:
    enabled: true
postgresql:
  fullnameOverride: 'pr-00-traction'
  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi
traction_api:
  image:
    tag: "ghcr.io/bcgov/traction-api:sha-87c2eb2"
    version: 'sha-87c2eb2'
    buildtime: '2022-01-20T22:37:11.102Z'
    pullPolicy: Always
  config:
    gunicornWorkers: 2
  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi
