multitenant_provider:
  manager:
    class_name: "traction_plugins.multitenant_provider.v1_0.manager.AskarMultitokenMultitenantManager"
    always_check_provided_wallet_key: true
  errors:
    on_unneeded_wallet_key: false
  token_expiry:
    units: days
    amount: 1

traction_innkeeper:
  innkeeper_wallet:
    tenant_id: innkeeper
    wallet_name: traction_innkeeper
    wallet_key: change-me
    print_key: true
    print_token: true
    connect_to_endorser: [
      {
        "endorser_alias": "endorser-1",
        "ledger_id": "bcovrin-test-1",
      },
      {
        "endorser_alias": "endorser-2",
        "ledger_id": "bcovrin-test-2",
      }
    ]
    create_public_did: ["bcovrin-test-1", "bcovrin-test-2"]
  reservation:
    auto_approve: true
    expiry_minutes: 2880
    auto_issuer: false
