apiVersion: v2
name: endorser
description: The Endorser service allows traction users to write ledger transactions.
type: application
version: 0.0.4
appVersion: 0.0.1
home: "https://github.com/bcgov/traction"
sources: ["https://github.com/bcgov/traction"]
engine: gotpl
maintainers:
  - email: tools@usingtechnolo.gy
    name: usingtechnology
    url: https://github.com/usingtechnology
  - email: jason.syrotuck@nttdata.com
    name: Jsyro
    url: https://github.com/Jsyro
  - email: iancostanzo@gmail.com
    name: IanCo
    url: https://github.com/ianco
dependencies:
  - name: postgresql
    version: 10.16.2
    repository: https://charts.bitnami.com/bitnami/
    condition: persistence.deployPostgres
