fullnameOverride: "traction-dts"
ingressSuffix: -dev.apps.silver.devops.gov.bc.ca
acapy:
  image:
    tag: "0.2.14"
    pullPolicy: Always
  plugin-config.yml:
    traction_innkeeper:
      innkeeper_wallet:
        print_key: true
        print_token: true
  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi
  argfile.yml:
    wallet-name: mywallet
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector:
        network.openshift.io/policy-group: ingress
tenant_proxy:
  image:
    tag: "0.2.14"
    pullPolicy: Always
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector:
        network.openshift.io/policy-group: ingress
ingress:
  annotations:
    route.openshift.io/termination: edge
postgresql:
  fullnameOverride: "traction-dts"
  auth:
    existingSecret: traction-dts-db
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: postgres-password
    # -- PostgreSQL Database to create.
    database: traction
    username: postgres
  primary:
    podLabels:
      backup: "true"
      env: dev
    resources:
      limits:
        cpu: 200m
        memory: 820Mi
      requests:
        cpu: 120m
        memory: 400Mi

