ingressSuffix: -dev.apps.silver.devops.gov.bc.ca
acapy:
  image:
    pullPolicy: Always
  secret:
    adminApiKey:
      generated: false
      value: "change-me"
    pluginInnkeeper:
      generated: false
      walletkey: "change-me"
      tenantid: "innkeeper"
  argfile.yml:
    wallet-name: default
  plugin-config.yml:
    traction_innkeeper:
      innkeeper_wallet:
        print_key: true
        print_token: true
        connect_to_endorser: [
          {
            "endorser_alias": "endorser",
            "ledger_id": "bcovrin-test",
          }
        ]
        create_public_did: ["bcovrin-test"]
      reservation:
        expiry_minutes: 2880
        auto_approve: true
        auto_issuer: true
  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector:
        network.openshift.io/policy-group: ingress
tenant_proxy:
  image:
    pullPolicy: Always
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector:
        network.openshift.io/policy-group: ingress
ingress:
  annotations:
    route.openshift.io/termination: edge
postgresql:
  primary:
    resources:
      limits:
        cpu: 200m
        memory: 820Mi
      requests:
        cpu: 120m
        memory: 400Mi
