global:
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca
  ledger: bcovrin-test
acapy:
  image:
    tag: "0.2.14"
    pullPolicy: Always
  secret:
    adminurl:
      generated: false
    pluginInnkeeper:
      generated: false
  pluginValues:
    tractionInnkeeper:
      printKey: true
      printToken: true
      reservationExpiryMinutes: 7200
  resources:
    limits:
      cpu: 400m
      memory: 1600Mi
    requests:
      cpu: 200m
      memory: 820Mi
  tails:
    enabled: true
postgresql:
  resources:
    limits:
      cpu: 400m
      memory: 1600Mi
    requests:
      cpu: 200m
      memory: 820Mi
tenant_proxy:
  image:
    tag: "0.2.14"
    pullPolicy: Always
