global:
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca
acapy:
  image:
    tag: "sha-f678ca9"
    pullPolicy: Always
  secret:
    adminurl:
      generated: false
      value: "change-me"
    pluginInnkeeper:
      generated: false
      walletkey: "change-me"
      tenantid: "innkeeper"
  plugins:
    basicmessageStorage: true
    connectionUpdate: true
    multitenantProvider: true
    tractionInnkeeper: true

  plugin-config.yml:
    traction_innkeeper:
      innkeeper_wallet:
        print_key: true
        print_token: true
      reservation:
        expiry_minutes: 2880
        auto_approve: false

  autoscaling:
    enabled: false

  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi

  argfile.yml:
    wallet-name: default

postgresql:
  primary:
    resources:
      limits:
        cpu: 200m
        memory: 820Mi
      requests:
        cpu: 120m
        memory: 400Mi

tenant_proxy:
  image:
    tag: "sha-f678ca9"
    pullPolicy: Always
  autoscaling:
    enabled: false
