name: Update Manifests
description: Update Manifest Repository
inputs:
  repository_key:
    required: true
    type: string
  repository:
    required: true
    type: string
  repository_checkout_path:
    required: true
    type: string
    default: manifests-repo
  charts_path:
    required: true
    type: string
    default: charts/traction
  target:
    required: true
    type: string
    default: 'dev'
  release_version:
    required: false
    type: string
  api_image_tag:
    required: false
    type: string
  api_image_version:
    required: false
    type: string
  api_image_buildtime:
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - name: Check out manifest repo
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ inputs.repository_key }}
        repository: ${{ inputs.repository }}
        path: ${{ inputs.repository_checkout_path }}

    - name: Set up git
      shell: bash
      run: |
        cd ./${{ inputs.repository_checkout_path }}
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Update release version
      shell: bash
      if: inputs.release_version != null && inputs.target == 'prod'
      run: |
        cd ./${{ inputs.repository_checkout_path }}/${{ inputs.charts_path }}
        yq eval '.appVersion = "${{ inputs.release_version }}"' -i Chart.yaml

    - name: Update Traction API image
      shell: bash
      if: inputs.api_image_tag != null
      run: |
        cd ./${{ inputs.repository_checkout_path }}/${{ inputs.charts_path }}
        yq eval '.traction_api.image.tag = "${{ inputs.api_image_tag }}"' -i values-${{ inputs.target }}.yaml
        yq eval '.traction_api.image.version = "${{ inputs.api_image_version }}"' -i values-${{ inputs.target }}.yaml
        yq eval '.traction_api.image.buildtime = "${{ inputs.api_image_buildtime }}"' -i values-${{ inputs.target }}.yaml

    - name: Push config changes
      shell: bash
      run: |
        cd ./${{ inputs.repository_checkout_path }}
        git commit -am "Update manifests for ${{ inputs.target }}"
        git push origin
