name: Deploy
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target environment for deployment: dev, test, prod'
        required: true
        default: 'dev'
jobs:

  deploy_manifest:
    name: Deploy Manifests
    runs-on: ubuntu-20.04
    
    steps:  
      - uses: actions/checkout@v2  

      - name: Check out manifest repo
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
          repository:  ${{ secrets.MANIFEST_REPO }}
          path: gitops

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          certificate_authority_data: ${{ secrets.OPENSHIFT_CA_CRT }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
      
      - name: Run Helm Charts
        shell: bash
        run: |
          cd ./gitops
          helm upgrade -f ./charts/traction/values.yaml -f ./charts/traction/values-${{ github.event.inputs.target }}.yaml bc0192-${{ github.event.inputs.target }}-traction ./charts/traction --install --wait    
