name: Deploy
on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'Target (github) environment for deployment: development, test, production'
        required: true
        default: 'development'
      config:
        description: 'Configuration for deployment (values-XXX.yaml): dev, test, prod, pr'
        required: true
        default: 'dev'
jobs:

  checkout_manifest:
    name: Checkout Manifests
    runs-on: ubuntu-20.04
    
    steps:  
      - uses: actions/checkout@v2  

      - name: Check out manifest repo
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
          repository:  ${{ secrets.MANIFEST_REPO }}
          path: gitops

      - name: Upload charts
        uses: actions/upload-artifact@v2
        with:
          name: charts
          path: gitops

  deploy_manifest:
    name: Deploy Manifests
    environment: ${{ github.event.inputs.deploy_env }}
    runs-on: ubuntu-20.04
    needs: 
      - checkout_manifest
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    
    steps:  
      - uses: actions/checkout@v2  

      - name: Download charts
        uses: actions/download-artifact@v2
        with:
          name: charts

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          certificate_authority_data: ${{ secrets.OPENSHIFT_CA_CRT }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
      
      - name: Run Helm Charts
        shell: bash
        run: |
          cd ./gitops
          helm upgrade -f ./charts/traction/values.yaml -f ./charts/traction/values-${{ github.event.inputs.config }}.yaml ${{ secrets.OPENSHIFT_NAMESPACE }}-traction ./charts/traction --install --wait    
