name: Deploy Traction
on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'Target (github) environment for deployment: development, test, production, tools'
        required: true
        default: 'development'
      ref:
        description: 'The branch, tag or SHA to checkout'
        required: true
        default: 'develop'
      instance_name:
        description: 'Instance name'
        required: true
        default: 'traction'

jobs:

  build_traction:
    name: 'Build Traction API'
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'
    steps:      
      - uses: actions/checkout@v3    
        with:
          ref: ${{ github.event.inputs.ref }}    

      - name: Build service
        uses: ./.github/actions/build_service
        id: builder
        with:
          ref: ${{ github.event.inputs.ref }}
          context: './services/traction'
          image_name: ${{ github.repository_owner}}/traction-api
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}
      image_version: ${{ steps.builder.outputs.image_version }}
      buildtime: ${{ steps.builder.outputs.buildtime }}

  build_acapy:
    name: 'Build Traction Aca-Py'
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'
    steps:      
      - uses: actions/checkout@v3        
        with:
          ref: ${{ github.event.inputs.ref }}    
      - name: Build Aca-Py Image
        uses: ./.github/actions/build_acapy
        id: builder
        with:
          ref: ${{ github.event.inputs.ref }}
          context: './plugins'
          dockerfile: './plugins/docker/Dockerfile'
          image_name: ${{ github.repository_owner}}/traction-plugins-acapy
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}
      image_version: ${{ steps.builder.outputs.image_version }}
      buildtime: ${{ steps.builder.outputs.buildtime }}

  deploy:
    name: Deploy Traction
    environment: ${{ github.event.inputs.deploy_env }}
    runs-on: ubuntu-latest
    needs: 
      - build_traction
      - build_acapy
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) && (github.repository_owner == 'bcgov') }}
    
    steps:  
      - uses: actions/checkout@v3  
        with:
          ref: ${{ github.event.inputs.ref }}    

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          certificate_authority_data: ${{ secrets.OPENSHIFT_CA_CRT }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Run Traction API Helm
        run: |
          yq eval '.global.fullnameOverride = "${{ github.event.inputs.instance_name }}"' -i ./charts/traction/values.yaml
          yq eval '.postgresql.fullnameOverride = "${{ github.event.inputs.instance_name }}"' -i ./charts/traction/values.yaml
          yq eval '.traction_api.image.tag = "${{ needs.build_traction.outputs.image_tag }}"' -i ./charts/traction/values-${{ github.event.inputs.deploy_env }}.yaml
          yq eval '.traction_api.image.version = "${{ needs.build_traction.outputs.image_version }}"' -i ./charts/traction/values-${{ github.event.inputs.deploy_env }}.yaml
          yq eval '.traction_api.image.buildtime = "${{ needs.build_traction.outputs.buildtime }}"' -i ./charts/traction/values-${{ github.event.inputs.deploy_env }}.yaml
          yq eval '.acapy.image.tag = "${{ needs.build_acapy.outputs.image_tag }}"' -i ./charts/traction/values-${{ github.event.inputs.deploy_env }}.yaml
          yq eval '.acapy.image.version = "${{ needs.build_acapy.outputs.image_version }}"' -i ./charts/traction/values-${{ github.event.inputs.deploy_env }}.yaml
          yq eval '.acapy.image.buildtime = "${{ needs.build_acapy.outputs.buildtime }}"' -i ./charts/traction/values-${{ github.event.inputs.deploy_env }}.yaml
          helm upgrade -f ./charts/traction/values.yaml -f ./charts/traction/values-${{ github.event.inputs.deploy_env }}.yaml "${{ github.event.inputs.instance_name }}" ./charts/traction --install --wait
