name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag: 
        required: false
        default: 'acapy-image'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd plugins && docker build . --file ./docker/Dockerfile --tag ${{ github.event.inputs.tag }}:$(date +%s)
