name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build_acapy:
    name: 'Build Traction Aca-Py Image'
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3        
      - name: Build Acapy
        uses: ./.github/actions/build_acapy
        id: builder
        with:
          context: './plugins'
          file: './plugins/docker/Dockerfile'
          image_name: ${{ github.repository_owner}}/traction-plugins-acapy
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}
      image_version: ${{ steps.builder.outputs.image_version }}
      buildtime: ${{ steps.builder.outputs.buildtime }}

