name: Push Instance to Develop
on:
  push:
    branches: 
      - develop
    paths:
      - 'services/**'

jobs:

  build_api:
    name: 'Build Traction API'
    runs-on: ubuntu-20.04
    steps:      
      - uses: actions/checkout@v2        
      - name: Build service
        uses: ./.github/actions/build_service
        id: builder
        with:
          context: './services/traction'
          image_name: ${{ github.repository_owner}}/traction-api
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}          
          registry_password: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}
      image_version: ${{ steps.builder.outputs.image_version }}
      buildtime: ${{ steps.builder.outputs.buildtime }}

  update_manifest:
    name: Update manifests
    runs-on: ubuntu-20.04
    needs: 
      - build_api
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    
    steps:  
      - uses: actions/checkout@v2  

      - name: Read Production Release values
        id: read_repo
        uses: ./.github/actions/read_manifest_repo
        with:
          target: prod
          repository_key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
          repository: ${{ secrets.MANIFEST_REPO }} 

      - name: Update repo
        uses: ./.github/actions/update_manifest_repo
        with:
          repository_key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
          repository: ${{ secrets.MANIFEST_REPO }}
          release_version: ${{ steps.read_repo.outputs.release_version }}
          api_image_tag: ${{ needs.build_api.outputs.image_tag }}
          api_image_version: ${{ needs.build_api.outputs.image_version }}
          api_image_buildtime: ${{ needs.build_api.outputs.buildtime }}



