name: Run Behaviour Driven Development Tests
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The branch, tag or SHA to checkout"
        required: true
        default: "develop"

jobs:
  setup_behave:
    name: "Build and Run Behave"
    environment: ${{ github.event.inputs.config_env }}
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'bcgov'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: run bdd
        working-directory: services/traction/bdd-tests
        env: |
          TRACTION_HOST=https://traction-api-dev.apps.silver.devops.gov.bc.ca
          INNKEEPER_PASSWORD=${{secrets.OPENSHIFT_TRACTION_DEV_INNKEEPER_PASSWORD}}          
        run: |
          docker-compose -f docker-compose.bdd.yml up --build
