name: Run Behvaiour Driven Development Tests
on:
  pull_request:
    branches:
      - develop
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 12 * * *"
  workflow_dispatch:
    inputs:
      deploy_env:
        description: "Target (github) environment for deployment: development"
        required: true
        default: "test"
      ref:
        description: "The branch, tag or SHA to checkout"
        required: true
        default: "develop"
      instance_name:
        description: "Instance name"
        required: true
        default: "bdd-tests-traction"

jobs:
  setup_behave:
    name: "Build Behave Test Image"
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'bcgov'
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - name: install libraries
        run: pip install -r /services/traction/requirements-bdd.txt
      - name: run behave
        run: |
          behave --define traction_host=https://traction-api-dev.apps.silver.devops.gov.bc.ca/ innkeeper_password=${{secrets.OPENSHIFT_TRACTION_DEV_INNKEEPER_PASSWORD}}
