name: Run Behaviour Driven Development Tests
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The branch, tag or SHA to checkout"
        required: true
        default: "develop"

jobs:
  setup_behave:
    name: "Build and Run Behave"
    environment: ${{ github.event.inputs.config_env }}
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'bcgov'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: run bdd
        working-directory: scripts        
        run: |
          docker-compose -f docker-compose.bdd.yml build
          docker-compose -f docker-compose.bdd.yml run bdd-tests -e TRACTION_HOST=${{secrets.BDD_TRACTION_HOST}} -e INNKEEPER_PASSWORD=${{secrets.BDD_TRACTION_INNKEEPER_PWD}}
