name: Run Integration Test
on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'Target (github) environment for deployment: development, test, production, tools'
        required: true
        default: 'test'
      ref:
        description: 'The branch, tag or SHA to checkout'
        required: true
        default: 'develop'
      instance_name:
        description: 'Instance name'
        required: true
        default: 'integtest-traction'

jobs:

  test:
    name: Run integration tests
    environment: ${{ github.event.inputs.deploy_env }}
    runs-on: ubuntu-20.04
    steps:  
      - uses: actions/checkout@v2  
        with:
          ref: ${{ github.event.inputs.ref }}    

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          certificate_authority_data: ${{ secrets.OPENSHIFT_CA_CRT }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Run tests in pod 
        run: |
          API_POD=$(oc get pods -o name --selector app.kubernetes.io/instance=${{ github.event.inputs.instance_name }},app.kubernetes.io/name=${{ github.event.inputs.instance_name }}-api)
          kubectl exec $API_POD -- pip install pytest-discord
          kubectl exec $API_POD -- pytest -p no:cacheprovider --asyncio-mode=strict -m integtest -rDp --discord-webhook=${{ secrets.PYTEST_DISCORD_WEBHOOK }}
          

